#Kopimi -- No license.

application: trackhub
version: 1
runtime: python
api_version: 1

handlers:
- url: /favicon.ico
  static_files: s/favicon.ico
  upload: s/favicon.ico
  expiration: "30d"  

- url: /s
  static_dir: s
  secure: optional

- url: /tasks/trackerStatus
  script: tasks/trackerStatus.py
  login: admin

- url: /
  script: root.py

- url: /announce
  script: main.py
  secure: optional

- url: /scrape
  script: main.py
  secure: optional

- url: .*
  script: main.py
  secure: optional

  


  
